version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: promotions_db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=promotion
      - MYSQL_ROOT_PASSWORD=mysql_password
    ports:
      - '3306:3306'
    volumes:
      - .docker/db:/var/lib/mysql
volumes:
  db:
    driver: local